# Generated by Django 5.2.4 on 2026-04-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('value', models.CharField(max_length=50, verbose_name='Nilai (misal: 1.000+)')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon (emoji atau nama)')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Statistik Dampak',
                'verbose_name_plural': 'Statistik Dampak',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImpactLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Wilayah')),
                ('province', models.CharField(max_length=100, verbose_name='Provinsi')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('beneficiaries_count', models.IntegerField(verbose_name='Jumlah Penerima Manfaat')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program', verbose_name='Program Terkait')),
            ],
            options={
                'verbose_name': 'Lokasi Dampak',
                'verbose_name_plural': 'Lokasi Dampak',
                'ordering': ['-beneficiaries_count'],
            },
        ),
    ]
