# Generated by Django 5.2.4 on 2026-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Kirim')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
            ],
            options={
                'verbose_name': 'Pesan Kontak',
                'verbose_name_plural': 'Pesan Kontak',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200, verbose_name='Nama Lembaga')),
                ('pic_name', models.CharField(max_length=200, verbose_name='Nama PIC')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telepon')),
                ('partnership_type', models.CharField(choices=[('donasi', 'Donasi / Sponsorship'), ('program', 'Kolaborasi Program'), ('logistik', 'Bantuan Logistik'), ('media', 'Media & Publikasi'), ('lainnya', 'Lainnya')], max_length=50, verbose_name='Jenis Kemitraan')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Kirim')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
            ],
            options={
                'verbose_name': 'Pengajuan Kemitraan',
                'verbose_name_plural': 'Pengajuan Kemitraan',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
