# Generated by Django 6.0.4 on 2026-04-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='partnershipinquiry',
            name='is_read',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('baru', 'Pesan Baru'), ('selesai', 'Sudah Selesai')], default='baru', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='partnershipinquiry',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru'), ('diskusi', 'Sedang Diskusi'), ('deal', 'Deal / Disetujui'), ('batal', 'Batal / Ditolak')], default='baru', max_length=20, verbose_name='Status'),
        ),
    ]
