# Generated by Django 5.2.4 on 2026-04-08 09:05

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Judul Artikel')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('laporan', 'Laporan Kegiatan'), ('edukasi', 'Artikel Edukasi'), ('berita', 'Berita')], max_length=50, verbose_name='Kategori')),
                ('excerpt', models.TextField(verbose_name='Ringkasan')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Konten Lengkap')),
                ('cover_image', models.URLField(blank=True, verbose_name='URL Cover (Cloudinary)')),
                ('author', models.CharField(default='Tim YAPU', max_length=100, verbose_name='Penulis')),
                ('published_at', models.DateTimeField(verbose_name='Tanggal Publikasi')),
                ('is_published', models.BooleanField(default=False, verbose_name='Diterbitkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program', verbose_name='Program Terkait')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-published_at'],
            },
        ),
    ]
