# Generated by Django 5.2.4 on 2026-04-08 09:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Program')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('sosial', 'Sosial'), ('kesehatan', 'Kesehatan'), ('lingkungan', 'Lingkungan'), ('keagamaan', 'Keagamaan'), ('pendidikan', 'Pendidikan'), ('ekonomi', 'Ekonomi')], max_length=50, verbose_name='Kategori')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('selesai', 'Selesai'), ('terencana', 'Terencana')], default='aktif', max_length=20, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Deskripsi Singkat')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Konten Detail')),
                ('image', models.URLField(blank=True, verbose_name='URL Foto (Cloudinary)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tampilkan di Beranda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Program',
                'ordering': ['-created_at'],
            },
        ),
    ]
