# Generated by Django 5.2.4 on 2026-04-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['display_order', 'created_at'], 'verbose_name': 'Program', 'verbose_name_plural': 'Program'},
        ),
        migrations.AddField(
            model_name='program',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil'),
        ),
    ]
