# Generated by Django 6.0.4 on 2026-04-11 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_options_program_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nama Kegiatan')),
                ('date_start', models.DateField(verbose_name='Tanggal Mulai')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('total_beneficiaries', models.PositiveIntegerField(default=0, verbose_name='Total Penerima Manfaat')),
                ('summary', models.TextField(blank=True, verbose_name='Ringkasan Kegiatan')),
                ('report_url', models.URLField(blank=True, verbose_name='Link Laporan/LPJ (opsional)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='programs.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Riwayat Pelaksanaan',
                'verbose_name_plural': 'Riwayat Pelaksanaan',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150, verbose_name='Kota / Lokasi')),
                ('beneficiaries', models.PositiveIntegerField(default=0, verbose_name='Penerima Manfaat di Lokasi Ini')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Catatan Tambahan')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='programs.programexecution', verbose_name='Pelaksanaan')),
            ],
            options={
                'verbose_name': 'Lokasi Pelaksanaan',
                'verbose_name_plural': 'Lokasi Pelaksanaan',
            },
        ),
    ]
