# Generated by Django 6.0.4 on 2026-04-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_programexecution_executionlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='beneficiary_label',
            field=models.CharField(default='Penerima Manfaat', help_text='Label untuk kolom penerima manfaat, misal: Pohon Ditanam, Peserta Hadir, Paket Disalurkan', max_length=100, verbose_name='Label Statistik'),
        ),
    ]
