# Generated by Django 5.2.4 on 2026-04-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('image', models.URLField(verbose_name='URL Foto (Cloudinary)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Upload')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.article', verbose_name='Artikel Terkait')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program', verbose_name='Program Terkait')),
            ],
            options={
                'verbose_name': 'Galeri Foto',
                'verbose_name_plural': 'Galeri Foto',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
