# Generated by Django 5.2.4 on 2026-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Mitra')),
                ('logo', models.URLField(blank=True, verbose_name='URL Logo (Cloudinary)')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Mitra',
                'verbose_name_plural': 'Mitra',
                'ordering': ['order'],
            },
        ),
    ]
