# Generated by Django 5.2.4 on 2026-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='No. HP/WhatsApp')),
                ('interest', models.CharField(choices=[('kesehatan', 'Kesehatan'), ('pendidikan', 'Pendidikan'), ('lingkungan', 'Lingkungan'), ('sosial', 'Sosial & Kemanusiaan'), ('teknologi', 'Teknologi & Dokumentasi'), ('logistik', 'Logistik & Operasional'), ('lainnya', 'Lainnya')], max_length=100, verbose_name='Bidang Minat')),
                ('domicile', models.CharField(max_length=100, verbose_name='Domisili')),
                ('message', models.TextField(blank=True, verbose_name='Pesan / Motivasi')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Daftar')),
            ],
            options={
                'verbose_name': 'Pendaftar Relawan',
                'verbose_name_plural': 'Pendaftar Relawan',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
