# Generated by Django 6.0.4 on 2026-04-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('baru', 'Pendaftar Baru'), ('dihubungi', 'Sedang Dihubungi'), ('aktif', 'Telah Bergabung'), ('batal', 'Batal / Tidak Aktif')], default='baru', max_length=20, verbose_name='Status'),
        ),
    ]
